# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_stat_printer', [dirname(__file__)])
        except ImportError:
            import _stat_printer
            return _stat_printer
        if fp is not None:
            try:
                _mod = imp.load_module('_stat_printer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _stat_printer = swig_import_helper()
    del swig_import_helper
else:
    import _stat_printer
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class stat_printer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, stat_printer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, stat_printer, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _stat_printer.new_stat_printer()
        try: self.this.append(this)
        except: self.this = this
    def get_mean(self): return _stat_printer.stat_printer_get_mean(self)
    __swig_getmethods__["success_fraction"] = _stat_printer.stat_printer_success_fraction_get
    if _newclass:success_fraction = _swig_property(_stat_printer.stat_printer_success_fraction_get)
    __swig_setmethods__["flips"] = _stat_printer.stat_printer_flips_set
    __swig_getmethods__["flips"] = _stat_printer.stat_printer_flips_get
    if _newclass:flips = _swig_property(_stat_printer.stat_printer_flips_get, _stat_printer.stat_printer_flips_set)
    __swig_setmethods__["flip"] = _stat_printer.stat_printer_flip_set
    __swig_getmethods__["flip"] = _stat_printer.stat_printer_flip_get
    if _newclass:flip = _swig_property(_stat_printer.stat_printer_flip_get, _stat_printer.stat_printer_flip_set)
    __swig_destroy__ = _stat_printer.delete_stat_printer
    __del__ = lambda self : None;
stat_printer_swigregister = _stat_printer.stat_printer_swigregister
stat_printer_swigregister(stat_printer)

# This file is compatible with both classic and new-style classes.


